// Code generated by MockGen. DO NOT EDIT.
// Source: ./account.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "go.uber.org/mock/gomock"
)

// MockAccountRepositorier is a mock of AccountRepositorier interface.
type MockAccountRepositorier struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositorierMockRecorder
}

// MockAccountRepositorierMockRecorder is the mock recorder for MockAccountRepositorier.
type MockAccountRepositorierMockRecorder struct {
	mock *MockAccountRepositorier
}

// NewMockAccountRepositorier creates a new mock instance.
func NewMockAccountRepositorier(ctrl *gomock.Controller) *MockAccountRepositorier {
	mock := &MockAccountRepositorier{ctrl: ctrl}
	mock.recorder = &MockAccountRepositorierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepositorier) EXPECT() *MockAccountRepositorierMockRecorder {
	return m.recorder
}
